---
title: "Code801"
author: "Marianne Huebner"
date: "August 21, 2016"
output: word_document
---

```{r, echo=FALSE}
setwd("~/Desktop/Teaching/801/Lectures")

library(ggplot2)
library(ggthemes)
library(extrafont)
```


*Most code is based on Christophe Lalanne's R Companion to Montgomery's Design and Analysis of Experiements (2005)*

## Probability distributions

For example, for the F distribution the R code format is \tt{df(x, df1, df2, log = FALSE)} where
\tt{df} gives the density, \tt{pf}  the distribution function, \tt{qf} is 
the quantile function, and \tt{rf} generates random deviates.
```{r, prob}

curve(dnorm(x,0,1), -3,3, ylab="normal density", col="blue")
curve(dnorm(x,1,1), -3,3, col="green", add=TRUE)
curve(dnorm(x,0,2), -3,3, col="red", add=TRUE)

#dt(x, df, ncp=0, log = FALSE)
#pt(q, df, ncp=0, lower.tail = TRUE, log.p = FALSE)
#qt(p, df,        lower.tail = TRUE, log.p = FALSE)
#rt(n, df)

curve(dt(x,10), -3,3, ylab="t density", col="green")
curve(dt(x,1), -3,3, col="blue", add=TRUE)
 legend(1,.35, c("df=10", "df=1"),col=c("green","blue"), lty=1)

#dchisq(x, df, ncp=0, log = FALSE)
curve(dchisq(x,2), 0,30, lty=1, ylab="chisquare density", col="green")
curve(dchisq(x,5),  lty=2, col="blue", add=TRUE)
curve(dchisq(x,10),  lty=3, col="red", add=TRUE)
legend(20,.5, c("df=2","df=5","df=10"),cex=1, col=c("green","blue", "red"), lty=1:3)
```



## Chapter 2


```{r, chap2tension}
set.seed(801)
# Tension Bond Strength data (Tab. 2-1, p. 24)
y1 <- c(16.85,16.40,17.21,16.35,16.52,17.04,16.96,17.15,16.59,16.57)
y2 <- c(16.62,16.75,17.37,17.12,16.98,16.87,17.34,17.02,17.08,17.27)
y <- data.frame(Modified=y1,Unmodified=y2)
y.means <- as.numeric(apply(y,2,mean))
#opar <- par(mfrow=c(2,1),mar=c(5,7,4,2),las=1) 
stripchart(y,xlab=expression("Strength (kgf/cm^2)"),pch=19) 
arrows(y.means,rep(1.5,2),y.means,c(1.1,1.9),length=.1) 
text(y.means,c(1.2,1.8),round(y.means,2),pos=4,cex=.8)
# Random deviates (instead of data from metal recovery used in the book) 
rd <- rnorm(200,mean=70,sd=5)
hist(rd,xlab="quantile",nclass=200, ylab="Relative frequency",
main="Random Normal Deviates\n N(70,5)") 
#par(opar)


boxplot(y,ylab="Strength (kgf/cm^2)",las=1)
```

```{r chap2ttest}
t.test(y1,y2,var.equal=TRUE)
as.numeric(diff(apply(y,2,mean)))
t.test(y1,y2)

qqnorm(y1)
qqline(y1)

```


```{r chap2hardness}
tmp<-c(7,3,3,4,8,3,2,9,5,4,6,3,5,3,8,2,4,9,4,5)
hardness <- data.frame(y = tmp, tip = gl(2,10))
t.test(y ~ tip, data = hardness, paired = TRUE)

with(hardness, plot(y[tip==1],y[tip==2],xlab="Tip 1",ylab="Tip 2"))
  abline(0,1)
  with(hardness, plot(y[tip==1]+y[tip==2],y[tip==1]-y[tip==2],
                      xlab="Tip 1 + Tip 2",ylab="Tip 1 - Tip 2",ylim=c(-3,3)))
abline(h=0)

#ignoring pairing
t.test(y ~ tip, data = hardness, var.equal = TRUE)

#nonparametric
wilcox.test(y1,y2)
wilcox.test(y~tip,data=hardness,paired=TRUE)
```